# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  build:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Test with pytest
#      run: |
#        pytest
    - name: Build (develop)
      if: github.ref == 'refs/heads/develop' 
      run: python unity_changelog_scraper.py --no-full-set --output-folder github-pages --print-versions
    - name: Build (master)
      if: github.ref == 'refs/heads/master'
      run: python unity_changelog_scraper.py --output-folder github-pages
    #- name: Github Pages Directory Listing
      # You may pin to the exact commit or the version.
      # uses: jayanta525/github-pages-directory-listing@00c9817e589e193a844dabbdc6a179d1f77d4376
    #  uses: jayanta525/github-pages-directory-listing@v2.0.0
    #  with:
        # folder to start index generations
    #    FOLDER: github-pages 
    - name: GitHub Pages v3
      # You may pin to the exact commit or the version.
      # uses: peaceiris/actions-github-pages@b80a30e9bf3c1ec596532c3813f0aff094f555e2
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        # 
        #deploy_key: # optional
        # 
        #github_token: # optional
        # 
        #personal_token: # optional
        # 
        #publish_branch: # optional, default is gh-pages
        # 
        publish_dir: github-pages # optional, default is public
        # 
        # external_repository: # optional
        # If empty commits should be made to the publication branch
        # allow_empty_commit: # optional, default is false
        # If existing files in the publish branch should be not removed before deploying
        keep_files: false # optional, default is false
        # Keep only the latest commit on a GitHub Pages branch
        #force_orphan: # optional, default is false
        # Set Git user.name
        #user_name: # optional
        # Set Git user.email
        #user_email: # optional
        # Set custom commit message
        #commit_message: # optional
        # Set tag name
        #tag_name: # optional
        # Set tag message
        #tag_message: # optional
