# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

permissions:
  contents: read

jobs:
  build:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#    - name: Test with pytest
#      run: |
#        pytest
    - name: Build (develop)
      if: github.ref == 'refs/heads/develop' 
      run: python unity_changelog_scraper.py --no-full-set --output-folder github-pages --print-versions
    - name: Build (master)
      if: github.ref == 'refs/heads/master'
      run: python unity_changelog_scraper.py --output-folder github-pages
    - name: Github Pages Directory Listing
      # You may pin to the exact commit or the version.
      # uses: jayanta525/github-pages-directory-listing@00c9817e589e193a844dabbdc6a179d1f77d4376
      uses: jayanta525/github-pages-directory-listing@v2.0.0
      with:
        # folder to start index generations
        FOLDER: github-pages 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./github-pages
